# Estágio de Build
FROM node:18-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Estágio de Produção
FROM nginx:stable-alpine
# O Vite gera a pasta 'dist' dentro de /app
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Certifique-se de que o nginx.conf está na mesma pasta que este dockerfile
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]